config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'top#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :users, only:[:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}" : time.strftime('%m月%d日')
  end
end

app/views/notifications/index.html.erb
<div class="container">
  <div class ="notify">
    <h2>お知らせ</h2>
    <ul>
      <% @notifications.each do |notification| %>
        <hr>
        <li style="list-style:none;">
          <% if notification.read == false %>
            <span>未読</span>
          <% else %>
            <span>既読</span>
          <% end %>
          <p>
            <%= notification.comment.user.try(:name) %>さんが
            あなたのブログ(<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>)にコメントしました。
          </p>
          <p><%= notification.created_at %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>